import { HiredMeRequest, HireRequest, Talent } from "./types";

export const talents: Talent[] = [
  {
    name: "GuitarMaster",
    username: "@guitarmaster",
    role: "Musician",
    category: "music",
    country: "us",
    availability: "available",
    hourlyRate: 80,
    verified: true,
    rating: 4.9,
    jobs: 120,
    rate: "$80/hr",
    bio: "Professional session guitarist with 10+ years of experience. I can...",
    tags: ["Music", "Guitarist", "Composer"],
    image:
      "https://images.unsplash.com/photo-1549213783-8284d0336c4f?w=100&h=100",
    followers: "45.2k",
  },
  {
    name: "Sarah_S",
    username: "@sarahdance",
    role: "Dancer",
    category: "performance",
    country: "us",
    availability: "busy",
    hourlyRate: 120,
    verified: false,
    rating: 5.0,
    jobs: 45,
    rate: "$120/hr",
    bio: "Contemporary dancer and choreographer. Available for music...",
    tags: ["Dance", "Choreography"],
    image:
      "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100",
    followers: "128k",
  },
  {
    name: "Jenny_Art",
    username: "@jennycolors",
    role: "Artist",
    category: "visual",
    country: "fr",
    availability: "available",
    hourlyRate: 95,
    verified: true,
    rating: 4.8,
    jobs: 82,
    rate: "$95/hr",
    bio: "Digital illustrator specializing in character design and concept art. ...",
    tags: ["Art", "Digital", "NFT"],
    image:
      "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&h=100",
    followers: "67.5k",
  },
  {
    name: "Tom_Tech",
    username: "@tomcodes",
    role: "Reviewer",
    category: "tech",
    country: "ca",
    availability: "available",
    hourlyRate: 250,
    verified: true,
    rating: 5.0,
    jobs: 210,
    rate: "$250/hr",
    bio: "Tech enthusiast and reviewer. I create high-quality unboxing and...",
    tags: ["Tech", "Reviewer"],
    image:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100",
    followers: "240k",
  },
  {
    name: "CreativeAgency",
    username: "@creative_hq",
    role: "Agency",
    category: "design",
    country: "de",
    availability: "busy",
    hourlyRate: 150,
    verified: true,
    rating: 4.7,
    jobs: "300+",
    rate: "$150/hr",
    bio: "Full-service creative design agency. We handle branding, logo design,...",
    tags: ["Design", "Branding"],
    image:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100",
    followers: "15.4k",
  },
  {
    name: "Anna K.",
    username: "@annadance",
    role: "Dancer",
    category: "performance",
    country: "it",
    availability: "available",
    hourlyRate: 75,
    verified: false,
    rating: 4.6,
    jobs: 28,
    rate: "$75/hr",
    bio: "Classical ballet dancer available for artistic photoshoots, music videos,...",
    tags: ["Dance", "Ballet"],
    image:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100",
    followers: "8.2k",
  },
];

export const hireRequests: HireRequest[] = [
  {
    id: "84920",
    title: "Video Editing for Campaign Q3",
    freelancer: "Sarah Jenkins",
    username: "@sarahcreative",
    avatar:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
    status: "IN PROGRESS",
    progress: 60,
    budget: 500,
    dueDate: "Oct 20, 2023",
    category: "Video Editing",
  },
  {
    id: "84915",
    title: "Logo Design for Startup",
    freelancer: "Davide Rossi",
    username: "@davide_design",
    avatar:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
    status: "COMPLETED",
    progress: 100,
    budget: 350,
    dueDate: "Oct 15, 2023",
    category: "Design",
  },
  {
    id: "84910",
    title: "Music Production for Podcast",
    freelancer: "GuitarMaster",
    username: "@guitarmaster",
    avatar:
      "https://images.unsplash.com/photo-1549213783-8284d0336c4f?w=200",
    status: "PENDING",
    progress: 20,
    budget: 800,
    dueDate: "Nov 5, 2023",
    category: "Music",
  },
];

export const hiredMeRequests: HiredMeRequest[] = [
  {
    id: "84925",
    title: "Website Redesign Project",
    client: "Tech Startup Inc",
    username: "@techstartup",
    avatar:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200",
    status: "ACTIVE",
    budget: 1200,
    startDate: "Oct 25, 2023",
    category: "Web Design",
  },
  {
    id: "84922",
    title: "Brand Identity Package",
    client: "Coffee Shop",
    username: "@coffeeshop",
    avatar:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200",
    status: "PENDING APPROVAL",
    budget: 650,
    startDate: "Oct 28, 2023",
    category: "Branding",
  },
];