import { DiscoverProfile } from "./types";

export const profiles: DiscoverProfile[] = [
  {
    id: "1",
    name: "GuitarMaster",
    username: "@guitarmaster",
    avatar:
      "https://images.unsplash.com/photo-1549213783-8284d0336c4f?w=100&h=100",
    role: "Musician",
    location: "Los Angeles",
    country: "us",
    bio: "Creating soulful riffs and melodies. Open for...",
    followers: "45.2k",
    posts: "128",
    verified: true,
    isFollowing: false,
    online: true,
  },
  {
    id: "2",
    name: "Sarah Sterling",
    username: "@sarah_dance",
    avatar:
      "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100",
    role: "Dancer",
    location: "New York",
    country: "us",
    bio: "Contemporary dancer & choreographer. Movin...",
    followers: "18.4k",
    posts: "342",
    verified: false,
    isFollowing: true,
    online: false,
  },
  {
    id: "3",
    name: "Davide Rossi",
    username: "@davide_design",
    avatar:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100",
    role: "Designer",
    location: "Milan",
    country: "it",
    bio: "Visual storyteller and brand identity speciali...",
    followers: "8.2k",
    posts: "56",
    projects: true,
    verified: true,
    isFollowing: false,
    online: true,
  },
  {
    id: "4",
    name: "Anna Klein",
    username: "@annak_photo",
    avatar:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100",
    role: "Photographer",
    location: "Berlin",
    country: "de",
    bio: "Capturing moments that last forever. Portrait &...",
    followers: "15.9k",
    posts: "890",
    label: "SHOTS",
    verified: false,
    isFollowing: false,
    online: false,
  },
  {
    id: "5",
    name: "James Lee",
    username: "@james_dev",
    avatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100",
    role: "Developer",
    location: "San Francisco",
    country: "us",
    bio: "Full-stack wizard building the future of...",
    followers: "5.3k",
    posts: "42",
    label: "REPOS",
    verified: false,
    isFollowing: false,
    online: true,
  },
  {
    id: "6",
    name: "Jenny Art",
    username: "@jenny_art",
    avatar:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100",
    role: "Artist",
    location: "Paris",
    country: "fr",
    bio: "Exploring colors and emotions through digit...",
    followers: "22.1k",
    posts: "105",
    label: "WORKS",
    verified: true,
    isFollowing: true,
    online: false,
  },
  {
    id: "7",
    name: "Mike Motion",
    username: "@mike_motion",
    avatar:
      "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=100&h=100",
    role: "Videographer",
    location: "Toronto",
    country: "ca",
    bio: "Cinematic storytelling through lens....",
    followers: "9.8k",
    posts: "64",
    label: "VIDEOS",
    verified: false,
    isFollowing: false,
    online: false,
  },
  {
    id: "8",
    name: "Lisa M.",
    username: "@lisa_model",
    avatar:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100",
    role: "Model",
    location: "Tokyo",
    country: "jp",
    bio: "Fashion and commercial model. Passionate abo...",
    followers: "30.5k",
    posts: "450",
    label: "PHOTOS",
    verified: false,
    isFollowing: false,
    online: true,
  },
];